# Numpy

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [13]:
import numpy as np
# 1
data = np.loadtxt('minutes_n_ingredients.csv',  int, skiprows=1, delimiter=',')
print(data[0:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [70]:
#2
mean_minutes = np.average(data[:, 1])
min_minutes = np.min(data[:, 1])
max_minutes = np.max(data[:, 1])
median_minutes = np.median(data[:, 1])

mean_n_ingredients = np.average(data[:, 2])
min_n_ingredients = np.min(data[:, 2])
max_n_ingredients = np.max(data[:, 2])
median_n_ingredients = np.median(data[:, 2])

print("Минуты:")
print("Среднее:", mean_minutes)
print("Минимум:", min_minutes)
print("Максимум:", max_minutes)
print("Медиана:", median_minutes)

print("\nИнгридиенты:")
print("Среднее:", mean_n_ingredients)
print("Минимум:", min_n_ingredients)
print("Максимум:", max_n_ingredients)
print("Медиана:", median_n_ingredients)

Минуты:
Среднее: 21601.00648
Минимум: 1
Максимум: 2147483647
Медиана: 40.0

Ингридиенты:
Среднее: 9.05528
Минимум: 1
Максимум: 39
Медиана: 9.0


In [27]:
#3
# Вычисляем квантиль 0.75
quantile_75 = np.quantile(data[:, 1], 0.75)

# Ограничиваем по значению квантиля 0.75
data[:, 1] = np.where(data[:, 1] > quantile_75, quantile_75, data[:, 1])

print("Квантиль:", quantile_75)
print(data)

Квантиль: 65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [32]:
#4
#data = np.loadtxt('minutes_n_ingredients.csv',  int, skiprows=1, delimiter=',')
# подсчет количества рецептов с продолжительностью, равной 0
num_zero_duration = np.count_nonzero(data[:, 1] == 0)

# замена значения 0 продолжительности на 1 в соответствующих строках
data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])

# вывод результатов
print(f"Количество рецептов с продолжительностью, равной 0: {num_zero_duration}")

Количество рецептов с продолжительностью, равной 0: 479


In [33]:
#5
unique_recipes = np.unique(data[:, 0])
print("Количество уникальных рецептов:", len(unique_recipes))

Количество уникальных рецептов: 100000


## Лабораторная работа №1.2

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [37]:
#6
unique_values = np.unique(data[:, 2])
print(len(unique_values))
print(unique_values)

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [39]:
#7
new_data = data[data[:, 2] <= 5]
print(new_data)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [40]:
#8
# расчет количества ингредиентов на одну минуту для каждого рецепта
ingr_per_min = data[:, 2] / data[:, 1]

# поиск максимального значения количества ингредиентов на одну минуту
max_ingr_per_min = ingr_per_min.max()

print("Максимальное значение количества ингредиентов на одну минуту:", max_ingr_per_min)

Максимальное значение количества ингредиентов на одну минуту: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [41]:
#9
# сортировка данных по убыванию времени приготовления
sorted_data = data[data[:, 1].argsort()[::-1]]

# выбор первых 100 рецептов из отсортированного массива
top_100_data = sorted_data[:100, :]

# вычисление среднего значения количества ингредиентов для топ-100 рецептов
mean_ingredients = np.mean(top_100_data[:, 2])

print("Среднее количество ингредиентов для топ-100 рецептов:", mean_ingredients)

Среднее количество ингредиентов для топ-100 рецептов: 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [43]:
#10
# Выбираем 10 случайных индексов
random_indexes = np.random.choice(len(data), size=10, replace=False)

# Извлекаем строки с этими индексами из датасета
random_recipes = data[random_indexes]

# Выводим информацию о выбранных рецептах
print(random_recipes)

[[431297     15      4]
 [ 87659     25     13]
 [217153      8      9]
 [ 41898    100     14]
 [167072     60     11]
 [ 83370     70      7]
 [344831     50      6]
 [235743     20      9]
 [ 98622     30      9]
 [ 79793    150     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [48]:
#11
# Вычисляем среднее количество ингредиентов в рецептах
mean_ingr = data[:, 2].mean()

# Вычисляем количество рецептов, количество ингредиентов в которых меньше среднего
less_than_mean = len(data[data[:, 2] < mean_ingr])

# Рассчитываем процент таких рецептов
percent_less_than_mean = less_than_mean / len(data) * 100

print("Процент рецептов, кол-во ингредиентов в которых меньше среднего:", percent_less_than_mean)

Процент рецептов, кол-во ингредиентов в которых меньше среднего: 58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [81]:
#12
# Задаем массивы-условия
time_cond = data[:, 1] <= 20
ingr_cond = data[:, 2] <= 5

# Массив, состоящий из единиц, длиной равной количеству строк в исходном датасете
simple_cond = np.zeros(len(data)).astype(int)

# Заменим значение элементов этого массива на 1 для тех строк, которые удовлетворяют обоим условиям
simple_cond[time_cond & ingr_cond] = 1

# Добавим этот столбец к исходному массиву
simple_data = np.c_[data, simple_cond]

print(simple_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [57]:
#13
simple_percent = simple_cond.mean() * 100
print("Процент 'простых' рецептов:",simple_percent)

Процент 'простых' рецептов: 9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [97]:
#14
data = np.loadtxt('minutes_n_ingredients.csv', int, skiprows=1, delimiter=',')

# Формирование масок
mask_short = data[:, 2] <= 10
mask_medium = (data[:, 2] > 10) & (data[:, 2] <= 20)
mask_long = data[:, 2] > 20

# Формирование массивов с фильтрацией по маскам
short = data[mask_short]
medium = data[mask_medium]
long = data[mask_long]

# Вычисление минимального числа строк среди массивов
min_cnt = min(short.shape[0], medium.shape[0], long.shape[0])

# Конкатенируем массивы для формирования трёхмерного массива
data = np.concatenate((np.expand_dims(short[:min_cnt], axis=1),
                      np.expand_dims(medium[:min_cnt], axis=1),
                      np.expand_dims(long[:min_cnt], axis=1)), axis=1)

print('Форма полученного массива:', data.shape)
print('Короткие рецепты:\n', data[:, 0, :])
print('Стандартные рецепты:\n', data[:, 1, :])
print('Длинные рецепты:\n', data[:, 2, :])

Форма полученного массива: (698, 3, 3)
Короткие рецепты:
 [[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 ...
 [353962    120      8]
 [ 54520     15      7]
 [ 85934      5      6]]
Стандартные рецепты:
 [[127244     60     16]
 [157911     60     14]
 [504666     65     20]
 ...
 [ 24955    110     12]
 [256126     30     11]
 [338378     45     11]]
Длинные рецепты:
 [[216748    120     21]
 [  3116     90     24]
 [487806     65     21]
 ...
 [188457    735     26]
 [ 51720     30     22]
 [451245    390     21]]
